[project]
authors = [
  "Oliver Kreylos <okreylos@ucdavis.edu>",
  "Tyler Shoemaker",
  "Nick Ulle <naulle@ucdavis.edu>"
]
channels = ["conda-forge"]
description = "Reader for the Intro to Remote Computing workshop series."
name = "intro_to_remote_computing"
platforms = ["linux-64", "osx-64", "win-64"]
version = "2024.winter.0"  # <year>.<quarter>.<revision #>

[tasks]
build = { cmd = "jupyter-book build .", description = "Build the reader." }
publish = { cmd = "ghp-import --no-jekyll --no-history --push _build/html", description = "Publish the reader to the `gh-pages` branch on GitHub." }
clean = { cmd = "rm -rf _build/", description = "Remove the build directory." }
rebuild = { depends-on = ["clean", "build"], description = "Remove the build directory and build the reader." }

[dependencies]
python = ">=3.12.7,<4"
jupyter-book = ">=1.0.3,<2"
ghp-import = ">=2.1.0,<3"
